---
- name: Install the package "htop"
  yum:
    name: htop
    state: present
  become: true

- debug:
    msg: "Ansible invoked inside {{ builder }}."
    
- name: Install the package "curl"
  yum:
    name: curl
    state: present
  become: true
